# Generated by Django 4.0.4 on 2022-06-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_phototag_latitude_alter_phototag_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototag',
            name='imgurl',
            field=models.ImageField(blank=True, null=True, upload_to='pic/'),
        ),
    ]
